apiVersion: apps/v1
kind: Deployment
metadata:
  name: malbullying-deployment
spec:
  selector:
    matchLabels:
      app: malbullying
  replicas: 2
  template:
    metadata:
      labels:
        app: malbullying
    spec:
      containers:
        - name: malbullying
          image: gaurav10223/malbullying:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080


---

apiVersion: v1
kind: Service
metadata:
  name: malbullying-ssvc
spec:
  selector:
    app: malbullying
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
      nodePort: 30080   
  type: NodePort         
